name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo '$GITHUB_CONTEXT'
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo '$COMMITS'
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo '$COMMIT_MESSAGES'
      - name: trying things out
        env:
          COMMIT_MESSAGES: ${{ contains(toJson(github.event.commits.*.message), '#skip')}}
        run: echo '$COMMIT_MESSAGES'
      - name: should run
        if: contains(toJson(github.event.commits.*.message), '#skip')
        run: echo "Hello!"

      # - name: working
      #   if: 'contains(toJSON(github.event.commits.*.message, '#skip'))'
      #   run: echo 'Commit message contains skip'
      # - name: not working
      #   if: '!contains(toJSON(github.event.commits.*.message, '#skip'))'
      #   run: echo 'Something went wrong :/'
